### ISSUE TITLE
Struggling to get Examples to Run

### ISSUE THREAD

**Issue by TM00** [TrimbleSolutionsCorporation/TSDRemotingAPIExamples#2]
Hi, I'm interested to start using the API. I've installed Visual Studio as per the guides, downloaded the examples and can't get them to run. I have a TSD 2021 model open (which it detects) but the moment it tries to get the document, an error presents itself.

I've tried the examples and the [getting started example](https://developer.tekla.com/tekla-structural-designer/documentation/get-started-tekla-structural-designer-open-api) presented in the docs. See below my code and output. I get an error when calling `tsd.GetDocumentAsync()`.

```
        public static async Task TSDTestAsync()
        {
            Console.WriteLine("Testing TSD....");

            // Retrieve all instances of Tekla Structural Designer running on local machine (API for connecting to instances on remote machines over TCP/IP network is also available)
            var tsdInstances = await ApplicationFactory.GetRunningApplicationsAsync();
            Console.WriteLine("got instances....");

            if (tsdInstances.Any())
            {
                Console.WriteLine("Here we simply get first instance found");

                // Here we simply get first instance found
                var tsd = tsdInstances.First();
                var title = await tsd.GetApplicationTitleAsync();
                Console.WriteLine($"got the first one!! {tsd} title: {title}");

                var document = await tsd.GetDocumentAsync();

                Console.WriteLine("And if there is a document");

                // And if there is a document
                if (document != null)
                {
                    // then we get its model
                    var model = await document.GetModelAsync();

                    // and from the model all members
                    var members = await model.GetMembersAsync(null);

                    // Finally we print total amount of members to standard output
                    Console.WriteLine($"Members in the model: {members.Count()}");
                }
            }
            else
            {
                Console.WriteLine("No running instance of Tekla Structural Designer found!");
            }
        }
    } 
```

Console output:

got instances....
Here we simply get first instance found

got the first one!! TSD.API.Remoting.Application title: 2022-07-13_5th 100mm mesh 
Event listening start!

'TSDApp1.exe' (CLR v4.0.30319: TSDApp1.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code
The operation failed with status: Unknown!

An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
The operation failed with status: Unknown!

Stack trace:

Unhandled Exception: System.InvalidOperationException: The operation failed with status: Unknown!
   at TSD.API.Remoting.Service.CommunicationHelpers.<CallTsdAsync>g__GetResponse|0_0[TResponse](<>c__DisplayClass0_0`1& )
   at TSD.API.Remoting.Service.CommunicationHelpers.<CallTsdAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TSD.API.Remoting.Application.<GetDocumentAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TSDApp1.Class1.<TSDTestAsync>d__0.MoveNext() in C:\VS Projects\TSDApp1\TSDApp1\TSDApp1\Class1.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TSDApp1.MainWindow.<OnClick>d__1.MoveNext() in C:\VS Projects\TSDApp1\TSDApp1\TSDApp1\MainWindow.xaml.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at TSDApp1.App.Main()
The program '[24148] TSDApp1.exe' has exited with code 0 (0x0).

I'm new to both C# and the API so if I'm missing something obvious, or you require more information, please advise.

**Comment by TM00** [comment]
Out of interested I downgraded my API version from 0.22.2 to 0.1.2, thinking it may be a version issue. The code ran a bit further but threw an exception at the following line:

`var members = await model.GetMemberAsync(null);`

This is the output and partial stack trace. (Note my TSD version number 21.5.0.85)

Here we simply get first instance found
got the first one!! TSD.API.Remoting.Application title: 2022-07-13_5th 100mm mesh version 21.5.0.85
Event listening start!
And if there is a document TSD.API.Remoting.Document.Document
then we get its model TSD.API.Remoting.Structure.Model
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
Exception thrown: 'Grpc.Core.RpcException' in mscorlib.dll
An exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll but was not handled in user code
Status(StatusCode="Internal", Detail="Failed to deserialize response message.")

An unhandled exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll
Status(StatusCode="Internal", Detail="Failed to deserialize response message.")


Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Failed to deserialize response message.")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

**Comment by MattSTrimble** [comment]
Hi

Thanks for your interest in the API!

The version 0.22.2 is designed to be compatible with Tekla Structural Designer 2022 Service Pack 2, which has been released this morning. If you run it alongside this version then it should work for you.

The earlier version 0.1.2 was originally designed to work with Tekla Structural Designer 2020 Service Pack 2.

I'd be really keen to hear if you have success with this, and anything you wish to share about how you would like to use the API and ideas for new features.

Kind regards,
Matt Sharman
Trimble

**Comment by TM00** [comment]
Hi @MattSTrimble ,

Thanks for getting back to me so quickly! I tested it the 2022 SP2 and it runs. Thanks so much. As a suggestion maybe state in the documentation which API version works with which TSD version. 

I'll play around with it for a while and let you know how I'm getting on. Currently the aim is to extract slab 2D results to create custom shear plots (peak shear, not X and Y individually). But I'll see how it goes as I'm new to C# (mostly Java experience to date) and the API.

Kind regards
Theo
